'use client';

import React, { useMemo } from 'react';
import * as Icons from '@tabler/icons-react';

interface DiffLine {
  type: 'add' | 'remove' | 'equal';
  content: string;
  oldLine?: number;
  newLine?: number;
}

function computeDiff(oldText: string, newText: string): DiffLine[] {
  const oldLines = oldText.split('\n');
  const newLines = newText.split('\n');
  const m = oldLines.length;
  const n = newLines.length;

  // LCS via DP
  const dp: number[][] = Array.from({ length: m + 1 }, () => new Array(n + 1).fill(0));
  for (let i = m - 1; i >= 0; i--) {
    for (let j = n - 1; j >= 0; j--) {
      if (oldLines[i] === newLines[j]) {
        dp[i][j] = dp[i + 1][j + 1] + 1;
      } else {
        dp[i][j] = Math.max(dp[i + 1][j], dp[i][j + 1]);
      }
    }
  }

  const result: DiffLine[] = [];
  let i = 0, j = 0;
  let oldLine = 1, newLine = 1;

  while (i < m || j < n) {
    if (i < m && j < n && oldLines[i] === newLines[j]) {
      result.push({ type: 'equal', content: oldLines[i], oldLine: oldLine++, newLine: newLine++ });
      i++; j++;
    } else if (j < n && (i >= m || dp[i][j + 1] >= dp[i + 1][j])) {
      result.push({ type: 'add', content: newLines[j], newLine: newLine++ });
      j++;
    } else {
      result.push({ type: 'remove', content: oldLines[i], oldLine: oldLine++ });
      i++;
    }
  }

  return result;
}

function collapseDiff(lines: DiffLine[], context = 3): Array<DiffLine | { type: 'hunk'; skipped: number }> {
  const changed = new Set<number>();
  lines.forEach((l, i) => { if (l.type !== 'equal') changed.add(i); });

  const visible = new Set<number>();
  changed.forEach((idx) => {
    for (let k = Math.max(0, idx - context); k <= Math.min(lines.length - 1, idx + context); k++) {
      visible.add(k);
    }
  });

  const result: Array<DiffLine | { type: 'hunk'; skipped: number }> = [];
  let skipping = false;
  let skipCount = 0;

  lines.forEach((line, i) => {
    if (visible.has(i)) {
      if (skipping && skipCount > 0) {
        result.push({ type: 'hunk', skipped: skipCount });
        skipCount = 0;
        skipping = false;
      }
      result.push(line);
    } else {
      skipping = true;
      skipCount++;
    }
  });

  if (skipping && skipCount > 0) {
    result.push({ type: 'hunk', skipped: skipCount });
  }

  return result;
}

export default function DiffReview({
  title,
  oldTitle,
  oldBody,
  newBody,
  isNew,
  onApprove,
  onCancel,
}: {
  title: string;
  oldTitle?: string;
  oldBody: string;
  newBody: string;
  isNew: boolean;
  onApprove: () => void;
  onCancel: () => void;
}) {
  const diff = useMemo(() => computeDiff(oldBody, newBody), [oldBody, newBody]);
  const collapsed = useMemo(() => collapseDiff(diff), [diff]);

  const addCount = diff.filter((l) => l.type === 'add').length;
  const removeCount = diff.filter((l) => l.type === 'remove').length;
  const titleChanged = oldTitle !== undefined && oldTitle !== title;

  return (
    <div className="fixed inset-0 z-[70] bg-black/50 flex items-center justify-center px-4 py-8">
      <div className="w-full max-w-[800px] max-h-[88vh] bg-white rounded-card shadow-2xl border border-hairline flex flex-col">
        {/* Header */}
        <div className="flex items-start justify-between px-5 py-4 border-b border-hairline shrink-0">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <div className="w-6 h-6 rounded-md bg-amber-100 grid place-items-center">
                <Icons.IconSparkles size={14} stroke={1.75} className="text-amber-600" />
              </div>
              <h2 className="font-serif text-[20px]">Review AI changes</h2>
            </div>
            <p className="text-[13px] text-muted">
              {isNew
                ? 'This is a new page generated by AI. Review before creating it.'
                : 'These changes were generated by AI. Review the diff before committing.'}
            </p>
          </div>
          <button
            onClick={onCancel}
            className="p-1.5 rounded-md hover:bg-black/[0.04] shrink-0"
          >
            <Icons.IconX size={16} stroke={1.75} />
          </button>
        </div>

        {/* Stats bar */}
        <div className="flex items-center gap-4 px-5 py-2.5 bg-sidebar border-b border-hairline text-[12px] shrink-0">
          {titleChanged && (
            <span className="flex items-center gap-1.5 text-amber-700 bg-amber-50 px-2 py-1 rounded-md border border-amber-200">
              <Icons.IconEdit size={12} stroke={1.75} />
              Title changed: <span className="line-through text-muted mr-1">{oldTitle}</span>→ <strong>{title}</strong>
            </span>
          )}
          {!isNew && (
            <>
              <span className="flex items-center gap-1 text-emerald-700">
                <Icons.IconPlus size={12} stroke={2} />
                {addCount} addition{addCount !== 1 ? 's' : ''}
              </span>
              <span className="flex items-center gap-1 text-red-600">
                <Icons.IconMinus size={12} stroke={2} />
                {removeCount} removal{removeCount !== 1 ? 's' : ''}
              </span>
            </>
          )}
          {isNew && (
            <span className="flex items-center gap-1 text-emerald-700">
              <Icons.IconFilePlus size={12} stroke={1.75} />
              New page · {addCount} lines
            </span>
          )}
          <span className="ml-auto text-muted">{title}</span>
        </div>

        {/* Diff view */}
        <div className="flex-1 overflow-y-auto overscroll-contain min-h-0">
          <div className="font-mono text-[12px] leading-5">
            {collapsed.map((entry, i) => {
              if ('skipped' in entry) {
                return (
                  <div
                    key={i}
                    className="px-4 py-1.5 bg-sidebar text-muted border-y border-hairline flex items-center gap-2"
                  >
                    <Icons.IconDotsVertical size={12} stroke={1.75} />
                    {entry.skipped} unchanged line{entry.skipped !== 1 ? 's' : ''}
                  </div>
                );
              }

              const line = entry as DiffLine;
              const isAdd = line.type === 'add';
              const isRemove = line.type === 'remove';

              return (
                <div
                  key={i}
                  className={`flex ${
                    isAdd
                      ? 'bg-emerald-50'
                      : isRemove
                      ? 'bg-red-50'
                      : 'bg-white'
                  }`}
                >
                  {/* Line numbers */}
                  <div className="w-10 text-right pr-2 py-0.5 text-muted select-none border-r border-hairline shrink-0 text-[11px] leading-5">
                    {line.oldLine ?? ''}
                  </div>
                  <div className="w-10 text-right pr-2 py-0.5 text-muted select-none border-r border-hairline shrink-0 text-[11px] leading-5">
                    {line.newLine ?? ''}
                  </div>
                  {/* Sign */}
                  <div
                    className={`w-6 text-center py-0.5 shrink-0 select-none font-bold ${
                      isAdd ? 'text-emerald-600' : isRemove ? 'text-red-500' : 'text-transparent'
                    }`}
                  >
                    {isAdd ? '+' : isRemove ? '−' : ' '}
                  </div>
                  {/* Content */}
                  <pre
                    className={`flex-1 py-0.5 pr-4 whitespace-pre-wrap break-all ${
                      isAdd ? 'text-emerald-900' : isRemove ? 'text-red-900 line-through opacity-70' : 'text-ink'
                    }`}
                  >
                    {line.content || ' '}
                  </pre>
                </div>
              );
            })}
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-between gap-3 px-5 py-3.5 border-t border-hairline shrink-0 bg-sidebar">
          <p className="text-[12px] text-muted">
            You can still go back and edit before committing.
          </p>
          <div className="flex items-center gap-2">
            <button
              onClick={onCancel}
              className="px-4 py-1.5 rounded-md text-[13px] text-muted hover:bg-black/[0.04]"
            >
              Back to editor
            </button>
            <button
              onClick={onApprove}
              className="flex items-center gap-1.5 px-4 py-1.5 rounded-md bg-brand text-white text-[13px] font-medium hover:bg-brand-600 transition-colors"
            >
              <Icons.IconCheck size={14} stroke={2} />
              Approve &amp; commit
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
